In [1]:
import os
os.chdir('/home/linhang/workbench/workbench/Earthquake_predictor/dataset')
from dataset_utils import *
from torch.utils.data import DataLoader
import torch.nn.functional as F
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_rows', None)  # 显示所有行
pd.set_option('display.max_columns', None)  # 显示所有列
pd.set_option('display.width', None)  # 自动调整显示宽度
pd.set_option('display.max_colwidth', None)  # 显示列的完整内容

In [3]:
import os
data_path = "/home/linhang/workbench/Earthquake_data/"
os.listdir(data_path)

['Japan', 'California']

In [4]:
area = "Japan"
data_area_path = data_path + area + "/"


window_size = 300
forecast_horizon = 14

lape_dim = 30

far_mask_delta = 30
dtw_delta = 10


gnss_data = pd.read_csv(data_area_path + "gnss_data.csv", index_col=0, parse_dates=True, low_memory=False).map(parse_str_list)
earthquake_data = pd.read_csv(data_area_path+"earthquake_data.csv", index_col=0, parse_dates=True)
energy_data = pd.read_csv(data_area_path+"energy_data.csv", index_col=0, parse_dates=True)
station_dict_use = pickle.load(open(data_area_path+"station_dict_use.pkl", "rb"))

es_geo_matrix = pd.read_csv(data_area_path+"es_geo_matrix.csv", index_col=0)
es_sem_matrix = pd.read_csv(data_area_path+"es_sem_matrix.csv", index_col=0)
gnss_geo_matrix = pd.read_csv(data_area_path+"gnss_geo_matrix.csv", index_col=0)

dataset_japan = EarthquakeGNSSDataset(area=area,earthquake_data=earthquake_data,es_geo_matrix=es_geo_matrix,es_sem_matrix=es_sem_matrix,
                                gnss_geo_matrix=gnss_geo_matrix,gnss_data=gnss_data,far_mask_delta=far_mask_delta,
                                dtw_delta=dtw_delta,lape_dim=lape_dim,
                                window_size=window_size,forecast_horizon=forecast_horizon,earthquake_threshold=4,missing_threshold=5)

In [5]:
area = "California"
data_area_path = data_path + area + "/"


window_size = 300
forecast_horizon = 14

lape_dim = 30

far_mask_delta = 30
dtw_delta = 10


gnss_data = pd.read_csv(data_area_path + "gnss_data.csv", index_col=0, parse_dates=True, low_memory=False).map(parse_str_list)
earthquake_data = pd.read_csv(data_area_path+"earthquake_data.csv", index_col=0, parse_dates=True)
energy_data = pd.read_csv(data_area_path+"energy_data.csv", index_col=0, parse_dates=True)
station_dict_use = pickle.load(open(data_area_path+"station_dict_use.pkl", "rb"))

es_geo_matrix = pd.read_csv(data_area_path+"es_geo_matrix.csv", index_col=0)
es_sem_matrix = pd.read_csv(data_area_path+"es_sem_matrix.csv", index_col=0)
gnss_geo_matrix = pd.read_csv(data_area_path+"gnss_geo_matrix.csv", index_col=0)

dataset_California = EarthquakeGNSSDataset(area=area,earthquake_data=earthquake_data,es_geo_matrix=es_geo_matrix,es_sem_matrix=es_sem_matrix,
                                gnss_geo_matrix=gnss_geo_matrix,gnss_data=gnss_data,far_mask_delta=far_mask_delta,
                                dtw_delta=dtw_delta,lape_dim=lape_dim,
                                window_size=window_size,forecast_horizon=forecast_horizon,earthquake_threshold=4)

In [6]:
for key in dataset_japan[0]:
    print(key,dataset_japan[0][key].shape)

log_energy_history torch.Size([22, 100, 1])
gnss_data_history torch.Size([1, 300, 4])
log_energy_future torch.Size([100, 1])
earthquake_data_future_day torch.Size([100])
es_geo_mask torch.Size([100, 100])
es_sem_mask torch.Size([100, 100])
gnss_geo_mask torch.Size([1, 1])
lap_ex torch.Size([100, 30])
lap_gnss torch.Size([1, 0])
earthquake_happen torch.Size([100])


In [7]:
for key in dataset_California[0]:
    print(key,dataset_California[0][key].shape)

log_energy_history torch.Size([22, 100, 1])
gnss_data_history torch.Size([56, 300, 4])
log_energy_future torch.Size([100, 1])
earthquake_data_future_day torch.Size([100])
es_geo_mask torch.Size([100, 100])
es_sem_mask torch.Size([100, 100])
gnss_geo_mask torch.Size([56, 56])
lap_ex torch.Size([100, 30])
lap_gnss torch.Size([56, 30])
earthquake_happen torch.Size([100])


In [8]:
region_datasets = {"Japan": dataset_japan, "California": dataset_California}
dataset = CombinedEarthquakeGNSSDataset(region_datasets)

In [9]:
print("Dataset length:", len(dataset),region_datasets["Japan"].__len__(),region_datasets["California"].__len__())

Dataset length: 11062 5531 5531


In [10]:
dataloader = DataLoader(dataset, batch_size=8, shuffle=True, collate_fn=dataset.collate_fn)
for batch in dataloader:
    print("Batch data:")
    for key, value in batch.items():
        print(key, value.shape)
    break

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False])
tensor([False, False, False, False,  True, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,

In [11]:
dataloader = DataLoader(dataset, batch_size=8, shuffle=True, collate_fn=dataset.collate_fn)
for batch in dataloader:
    print("Batch data:")
    for key, value in batch.items():
        print(key, value.shape)
    break

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False])
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,